### PR TITLE
Add News SubElement

### PR DESCRIPTION
**Pull request by sherault**
Add the SubElement for news for Google News

https://support.google.com/news/publisher/answer/74288?hl=fr

### CODE REVIEW

**Comment by ThePixelDeveloper** [comment]
Can you add an example to the README and I'll merge it.

Thanks for contributing

**Comment by sherault** [comment]
Done, let me know if you need more info regarding this subelement.

Thanks you for this package

**Comment by ThePixelDeveloper** [comment]
Looks good to me, merged.

**Comment by sherault** [comment]
Great, thanks ! :)

**Pull request merged**
